name: Build and Deploy to cloudflare
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to cloudflare
        uses: demosjarco/wrangler-action-node@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy ./ --project-name=${{ secrets.PROJECT_NAME }}
